# Generated by Django 4.0.2 on 2022-06-13 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 15, 17, 32, 290774, tzinfo=utc)),
        ),
    ]
